const languageList = [
    { name: "English", iso2: "en", iso3: "eng" },
    { name: "Spanish", iso2: "es", iso3: "spa" },
    { name: "French", iso2: "fr", iso3: "fra" },
    { name: "German", iso2: "de", iso3: "deu" },
    { name: "Chinese", iso2: "zh", iso3: "zho" },
    { name: "Japanese", iso2: "ja", iso3: "jpn" },
    { name: "Portuguese", iso2: "pt", iso3: "por" },
    { name: "Russian", iso2: "ru", iso3: "rus" },
    { name: "Arabic", iso2: "ar", iso3: "ara" },
    { name: "Hindi", iso2: "hi", iso3: "hin" },
    { name: "Italian", iso2: "it", iso3: "ita" },
    { name: "Korean", iso2: "ko", iso3: "kor" },
    { name: "Dutch", iso2: "nl", iso3: "nld" },
    { name: "Greek", iso2: "el", iso3: "ell" },
    { name: "Swedish", iso2: "sv", iso3: "swe" },
    { name: "Turkish", iso2: "tr", iso3: "tur" },
    { name: "Polish", iso2: "pl", iso3: "pol" },
    { name: "Danish", iso2: "da", iso3: "dan" },
    { name: "Finnish", iso2: "fi", iso3: "fin" },
    { name: "Hebrew", iso2: "he", iso3: "heb" },
    { name: "Norwegian", iso2: "no", iso3: "nor" },
    { name: "Thai", iso2: "th", iso3: "tha" },
    { name: "Czech", iso2: "cs", iso3: "ces" },
    { name: "Hungarian", iso2: "hu", iso3: "hun" },
    { name: "Romanian", iso2: "ro", iso3: "ron" },
];

export default languageList;
